# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <compute_ab_g_stc__cohort_race__nih>
  # <compute_ab_g_stc__cohort_ethnrace__leg>
  # <compute_ab_g_stc__cohort_ethnrace__mhisp>
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  # <compute_ab_g_dyn__cohort_income__hhold__6lvl>
  # <compute_ab_g_dyn__cohort_income__hhold__3lvl>
  # <compute_ab_g_dyn__cohort_edu__cgs>
  # <compute_ab_g_dyn__cohort_prtnrshp__employ>
  # <compute_fc_y_eut__ethn_mean>
  # <compute_fc_y_eut__ethn_nm>
  # <compute_mh_p_eatq__surg_mean>
  # <compute_mh_p_eatq__actv_mean>
  # <compute_mh_p_eatq__affl_mean>
  # <compute_mh_p_eatq__depm_mean>
  # <compute_mh_p_eatq__aggr_mean>
  # <compute_mh_p_eatq__attn_mean>
  # <compute_mh_p_eatq__fear_mean>
  # <compute_mh_p_eatq__inhib_mean>
  # <compute_mh_p_eatq__shy_mean>
  # <compute_mh_p_eatq__frust_mean>
  # <compute_mh_p_ple__severity_sum>
  # <compute_mh_p_ple__severity_mean>
  # <compute_mh_p_ple__severity__good_sum>
  # <compute_mh_p_ple__severity__good_mean>
  # <compute_mh_p_ple__severity__bad_sum>
  # <compute_mh_p_ple__severity__bad_mean>
  # <compute_mh_p_ple__exp__good_count>
  # <compute_mh_p_ple__exp__bad_count>
  # <compute_mh_p_ple__severity_sum__v01>
  # <compute_mh_p_ple__severity_mean__v01>
  # <compute_mh_p_ple__severity__good_sum__v01>
  # <compute_mh_p_ple__severity__good_mean__v01>
  # <compute_mh_p_ple__severity__bad_sum__v01>
  # <compute_mh_p_ple__severity__bad_mean__v01>
  # <compute_mh_p_ple__exp__good_count__v01>
  # <compute_mh_p_ple__exp__bad_count__v01>
  # <compute_mh_p_ple__severity_sum__v02>
  # <compute_mh_p_ple__severity_mean__v02>
  # <compute_mh_p_ple__severity__good_sum__v02>
  # <compute_mh_p_ple__severity__good_mean__v02>
  # <compute_mh_p_ple__severity__bad_sum__v02>
  # <compute_mh_p_ple__severity__bad_mean__v02>
  # <compute_mh_p_ple__exp__good_count__v02>
  # <compute_mh_p_ple__exp__bad_count__v02>
  # <compute_mh_p_ple__severity_sum__v03>
  # <compute_mh_p_ple__severity_mean__v03>
  # <compute_mh_p_ple__severity__good_sum__v03>
  # <compute_mh_p_ple__severity__good_mean__v03>
  # <compute_mh_p_ple__severity__bad_sum__v03>
  # <compute_mh_p_ple__severity__bad_mean__v03>
  # <compute_mh_p_ple__exp__good_count__v03>
  # <compute_mh_p_ple__exp__bad_count__v03>
  # <compute_mh_p_ple__severity_sum__v04>
  # <compute_mh_p_ple__severity_mean__v04>
  # <compute_mh_p_ple__severity__good_sum__v04>
  # <compute_mh_p_ple__severity__good_mean__v04>
  # <compute_mh_p_ple__severity__bad_sum__v04>
  # <compute_mh_p_ple__severity__bad_mean__v04>
  # <compute_mh_p_ple__exp__good_count__v04>
  # <compute_mh_p_ple__exp__bad_count__v04>
  # <compute_mh_y_ple__severity_sum>
  # <compute_mh_y_ple__severity_mean>
  # <compute_mh_y_ple__severity__good_sum>
  # <compute_mh_y_ple__severity__good_mean>
  # <compute_mh_y_ple__severity__bad_sum>
  # <compute_mh_y_ple__severity__bad_mean>
  # <compute_mh_y_ple__exp__good_count>
  # <compute_mh_y_ple__exp__bad_count>
  # <compute_mh_y_ple__severity_sum__v01>
  # <compute_mh_y_ple__severity_mean__v01>
  # <compute_mh_y_ple__severity__good_sum__v01>
  # <compute_mh_y_ple__severity__good_mean__v01>
  # <compute_mh_y_ple__severity__bad_sum__v01>
  # <compute_mh_y_ple__severity__bad_mean__v01>
  # <compute_mh_y_ple__exp__good_count__v01>
  # <compute_mh_y_ple__exp__bad_count__v01>
  # <compute_mh_y_ple__severity_sum__v02>
  # <compute_mh_y_ple__severity_mean__v02>
  # <compute_mh_y_ple__severity__good_sum__v02>
  # <compute_mh_y_ple__severity__good_mean__v02>
  # <compute_mh_y_ple__severity__bad_sum__v02>
  # <compute_mh_y_ple__severity__bad_mean__v02>
  # <compute_mh_y_ple__exp__good_count__v02>
  # <compute_mh_y_ple__exp__bad_count__v02>
  # <compute_mh_y_ple__severity_sum__v03>
  # <compute_mh_y_ple__severity_mean__v03>
  # <compute_mh_y_ple__severity__good_sum__v03>
  # <compute_mh_y_ple__severity__good_mean__v03>
  # <compute_mh_y_ple__severity__bad_sum__v03>
  # <compute_mh_y_ple__severity__bad_mean__v03>
  # <compute_mh_y_ple__exp__good_count__v03>
  # <compute_mh_y_ple__exp__bad_count__v03>
  # <compute_mh_y_pps__bother_nm>
  # <compute_mh_y_pps__bother__yes_count>
  # <compute_mh_y_pps__bother__no_count>
  # <compute_mh_y_pps__severity_nm>
  # <compute_mh_y_pps__severity_score>
  # <compute_mh_y_pps__severity_mean>
  # <product_vars>
  # <ss_mean_mh_ple>
  # <ss_sum_mh_ple>
  # <ss_nm_mh_ple>
  # <compute_mh_p_abcl__cg2_sex>
  # <compute_nc_p_bdefs__sympt_count>
  # <compute_nc_y_ehis_score>
  # <compute_nt_p_yst__screen__wkdy_nm>
  # <compute_nt_p_yst__screen__wkdy_sum>
  # <compute_nt_p_yst__screen__wknd_nm>
  # <compute_nt_p_yst__screen__wknd_sum>
  # <compute_nt_y_stq__screen__wkdy_nm>
  # <compute_nt_y_stq__screen__wkdy_sum>
  # <compute_nt_y_stq__screen__wknd_nm>
  # <compute_nt_y_stq__screen__wknd_sum>
  # <compute_ph_p_dhx_birthweight>
  # <compute_ph_p_otbi__loc__30m_count>
  # <compute_ph_p_otbi__loc__30m_nm>
  # <compute_ph_p_otbi__loc_count>
  # <compute_ph_p_otbi__loc_nm>
  # <compute_ph_p_otbi__rpt_count>
  # <compute_ph_p_otbi__rpt_nm>
  # <compute_ph_p_otbi__loc_tbiage>
  # <compute_ph_p_otbi__loc__tbiage_nm>
  # <compute_ph_p_otbi__loc_before15>
  # <compute_ph_p_otbi_tbiworst>
  # <compute_ph_y_pds__m_categ>
  # <compute_ph_y_pds__f_categ>
  # <compute_ph_p_pds__m_categ>
  # <compute_ph_p_pds__f_categ>
  # <compute_ph_y_anthr__height_mean>
  # <compute_ph_y_anthr__weight_mean>
  # <compute_ph_y_bp__sys_mean>
  # <compute_ph_y_bp__sys_nm>
  # <compute_ph_y_bp__dia_mean>
  # <compute_ph_y_bp__dia_nm>
  # <compute_ph_y_bp__hrate_mean>
  # <compute_ph_y_bp__hrate_nm>
  # <compute_ph_y_mctq__fd__sleep_latent>
  # <compute_ph_y_mctq__fd__sleep_inertia>
  # <compute_ph_y_mctq__fd__sleep__waso_sum>
  # <compute_ph_y_mctq__sd_count>
  # <compute_ph_y_mctq__sd__sleep_inertia>
  # <compute_ph_y_mctq__sd__sleep_latent>
  # <compute_ph_y_mctq__sd__sleep__waso_sum>
  # <compute_ph_y_mctq__fd__sleep__onset__36h_t>
  # <compute_ph_y_mctq__fd__bed__end__36h_t>
  # <compute_ph_y_mctq__fd__sleep__onset__24h_t>
  # <compute_ph_y_mctq__fd__bed__end__24h_t>
  # <compute_ph_y_mctq__fd_count>
  # <compute_ph_y_mctq__sd__sleep__onset__36h_t>
  # <compute_ph_y_mctq__sd__bed__end__36h_t>
  # <compute_ph_y_mctq__sd__sleep__onset__24h_t>
  # <compute_ph_y_mctq__sd__bed__end__24h_t>
  # <compute_ph_y_mctq__fd__sleep_dur>
  # <compute_ph_y_mctq__fd__sleep_period>
  # <compute_ph_y_mctq__fd__bed_sum>
  # <compute_ph_y_mctq__sd__sleep_dur>
  # <compute_ph_y_mctq__sd__sleep_period>
  # <compute_ph_y_mctq__sd__bed_sum>
  # <compute_ph_y_mctq__fd__sleep__mid__24h_t>
  # <compute_ph_y_mctq__fd__sleep__mid__36h_t>
  # <compute_ph_y_mctq__sd__sleep__mid__24h_t>
  # <compute_ph_y_mctq__sleep_dur>
  # <compute_ph_y_mctq__sleep_loss>
  # <compute_ph_y_mctq__sd__sleep__mid__36h_t>
  # <compute_ph_y_mctq__sleep_period>
  # <compute_ph_y_mctq__raw__36h_chrono>
  # <compute_ph_y_mctq_chrono>
  # <compute_ph_y_mctq__socjl_rel>
  # <compute_ph_y_mctq__socjl_absl>
  # <compute_ph_y_mctq_outlier>
  # <convert_time_mctq>
  # <compute_su_y_alchss_count>
  # <compute_su_y_mjsre_sum>
  # <compute_su_y_nicsre__vape_sum>
  # <compute_su_y_nicsre__vape_nm>
  # <compute_caff_weekly>
  # <compute_su_y_caff__coffee_sum>
  # <compute_su_y_caff__energy__drink_sum>
  # <compute_su_y_caff__energy__shot_sum>
  # <compute_su_y_caff__energy_sum>
  # <compute_su_y_caff__espres_sum>
  # <compute_su_y_caff__oth_sum>
  # <compute_su_y_caff__soda_sum>
  # <compute_su_y_caff__suppl_sum>
  # <compute_su_y_caff__tea_sum>
  # <compute_tlfb_abst>
  # <compute_tlfb_dt>
  # <compute_tlfb_maxdose>
  # <compute_tlfb_mean>
  # <compute_tlfb_totdose>
  # <compute_tlfb_ud>
  # <compute_su_y_sui__onset_useage>
  # <compute_su_y_sui__reg_useage>
  # <compute_su_y_sui__last__day_count>
  # <ss_mean>
  # <ss_sum>
  # <ss_nm>
  # <ss_count>
  # <ss_max>
  # <ss_prsum>
  # <ss_tscore>
  # <ss_count_cond>
  # <ss_mean_pos>
  # <recode_levels>
  # <combine_cols>
  # <combine_levels>
  # <check_assign_na>
  # <create_session_num>
  # <make_static>
  ":=",
  # <compute_nt_y_stq__screen__wkdy_nm>
  # <compute_nt_y_stq__screen__wkdy_sum>
  # <compute_nt_y_stq__screen__wknd_nm>
  # <compute_nt_y_stq__screen__wknd_sum>
  # <compute_ph_y_bp__sys_nm>
  # <compute_ph_y_bp__dia_nm>
  # <compute_ph_y_bp__hrate_nm>
  # <ss_count>
  # <get_tscore_tbl>
  ".",
  # <compute_su_y_sui__last__day_count>
  "ab_g_dyn__visit_dtt",
  # <compute_su_y_sui__onset_useage>
  # <compute_su_y_sui__reg_useage>
  "ab_g_stc__cohort_dob",
  # <compute_ab_g_dyn__cohort_income__hhold__6lvl>
  "ab_p_demo__income__hhold_001",
  # <compute_ab_g_dyn__cohort_income__hhold__6lvl>
  "ab_p_demo__income__hhold_001__v01",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___0",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___10",
  # <compute_ab_g_stc__cohort_race__nih>
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  "ab_p_demo__race_001___11",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___12",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___13",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___14",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___15",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___16",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___17",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___18",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___19",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___20",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___21",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___22",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___23",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___24",
  # <compute_ab_g_stc__cohort_race__nih>
  "ab_p_demo__race_001___25",
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  "ab_p_demo__race_001__v01___11",
  # <ss_tscore>
  "age_max",
  # <ss_tscore>
  "age_min",
  # <compute_ph_p_dhx_birthweight>
  # <compute_ph_p_otbi__tbi1a>
  # <compute_ph_p_otbi__tbi1b>
  # <compute_ph_p_otbi__tbi2>
  # <compute_ph_p_otbi__tbi3>
  # <compute_ph_p_otbi__tbi4>
  # <compute_ph_p_otbi__tbi5>
  "baseline",
  # <compute_mh_p_ple__severity_sum>
  # <compute_mh_p_ple__severity_mean>
  # <compute_mh_p_ple__severity__good_sum>
  # <compute_mh_p_ple__severity__good_mean>
  # <compute_mh_p_ple__severity__bad_sum>
  # <compute_mh_p_ple__severity__bad_mean>
  # <compute_mh_p_ple__exp__good_count>
  # <compute_mh_p_ple__exp__bad_count>
  # <compute_mh_p_ple__severity_sum__v01>
  # <compute_mh_p_ple__severity_mean__v01>
  # <compute_mh_p_ple__severity__good_sum__v01>
  # <compute_mh_p_ple__severity__good_mean__v01>
  # <compute_mh_p_ple__severity__bad_sum__v01>
  # <compute_mh_p_ple__severity__bad_mean__v01>
  # <compute_mh_p_ple__exp__good_count__v01>
  # <compute_mh_p_ple__exp__bad_count__v01>
  # <compute_mh_p_ple__severity_sum__v02>
  # <compute_mh_p_ple__severity_mean__v02>
  # <compute_mh_p_ple__severity__good_sum__v02>
  # <compute_mh_p_ple__severity__good_mean__v02>
  # <compute_mh_p_ple__severity__bad_sum__v02>
  # <compute_mh_p_ple__severity__bad_mean__v02>
  # <compute_mh_p_ple__exp__good_count__v02>
  # <compute_mh_p_ple__exp__bad_count__v02>
  # <compute_mh_p_ple__severity_sum__v03>
  # <compute_mh_p_ple__severity_mean__v03>
  # <compute_mh_p_ple__severity__good_sum__v03>
  # <compute_mh_p_ple__severity__good_mean__v03>
  # <compute_mh_p_ple__severity__bad_sum__v03>
  # <compute_mh_p_ple__severity__bad_mean__v03>
  # <compute_mh_p_ple__exp__good_count__v03>
  # <compute_mh_p_ple__exp__bad_count__v03>
  # <compute_mh_p_ple__severity_sum__v04>
  # <compute_mh_p_ple__severity_mean__v04>
  # <compute_mh_p_ple__severity__good_sum__v04>
  # <compute_mh_p_ple__severity__good_mean__v04>
  # <compute_mh_p_ple__severity__bad_sum__v04>
  # <compute_mh_p_ple__severity__bad_mean__v04>
  # <compute_mh_p_ple__exp__good_count__v04>
  # <compute_mh_p_ple__exp__bad_count__v04>
  # <compute_mh_y_ple__severity_sum>
  # <compute_mh_y_ple__severity_mean>
  # <compute_mh_y_ple__severity__good_sum>
  # <compute_mh_y_ple__severity__good_mean>
  # <compute_mh_y_ple__severity__bad_sum>
  # <compute_mh_y_ple__severity__bad_mean>
  # <compute_mh_y_ple__exp__good_count>
  # <compute_mh_y_ple__exp__bad_count>
  # <compute_mh_y_ple__severity_sum__v01>
  # <compute_mh_y_ple__severity_mean__v01>
  # <compute_mh_y_ple__severity__good_sum__v01>
  # <compute_mh_y_ple__severity__good_mean__v01>
  # <compute_mh_y_ple__severity__bad_sum__v01>
  # <compute_mh_y_ple__severity__bad_mean__v01>
  # <compute_mh_y_ple__exp__good_count__v01>
  # <compute_mh_y_ple__exp__bad_count__v01>
  # <compute_mh_y_ple__severity_sum__v02>
  # <compute_mh_y_ple__severity_mean__v02>
  # <compute_mh_y_ple__severity__good_sum__v02>
  # <compute_mh_y_ple__severity__good_mean__v02>
  # <compute_mh_y_ple__severity__bad_sum__v02>
  # <compute_mh_y_ple__severity__bad_mean__v02>
  # <compute_mh_y_ple__exp__good_count__v02>
  # <compute_mh_y_ple__exp__bad_count__v02>
  # <compute_mh_y_ple__severity_sum__v03>
  # <compute_mh_y_ple__severity_mean__v03>
  # <compute_mh_y_ple__severity__good_sum__v03>
  # <compute_mh_y_ple__severity__good_mean__v03>
  # <compute_mh_y_ple__severity__bad_sum__v03>
  # <compute_mh_y_ple__severity__bad_mean__v03>
  # <compute_mh_y_ple__exp__good_count__v03>
  # <compute_mh_y_ple__exp__bad_count__v03>
  "count_internal",
  # <compute_tlfb_abst>
  # <filter_tlfb>
  "dt_tlfb",
  # <compute_tlfb_abst>
  # <compute_tlfb_dt>
  # <compute_tlfb_mean>
  # <compute_tlfb_ud>
  # <filter_tlfb>
  # <filter_co_use>
  "dt_use",
  # <filter_tlfb>
  "dt_use_wknd",
  # <compute_mh_p_ple__severity__good_sum>
  # <compute_mh_p_ple__severity__good_mean>
  # <compute_mh_p_ple__severity__bad_sum>
  # <compute_mh_p_ple__severity__bad_mean>
  # <compute_mh_p_ple__severity__good_sum__v01>
  # <compute_mh_p_ple__severity__good_mean__v01>
  # <compute_mh_p_ple__severity__bad_sum__v01>
  # <compute_mh_p_ple__severity__bad_mean__v01>
  # <compute_mh_p_ple__severity__good_sum__v02>
  # <compute_mh_p_ple__severity__good_mean__v02>
  # <compute_mh_p_ple__severity__bad_sum__v02>
  # <compute_mh_p_ple__severity__bad_mean__v02>
  # <compute_mh_p_ple__severity__good_sum__v03>
  # <compute_mh_p_ple__severity__good_mean__v03>
  # <compute_mh_p_ple__severity__bad_sum__v03>
  # <compute_mh_p_ple__severity__bad_mean__v03>
  # <compute_mh_p_ple__severity__good_sum__v04>
  # <compute_mh_p_ple__severity__good_mean__v04>
  # <compute_mh_p_ple__severity__bad_sum__v04>
  # <compute_mh_p_ple__severity__bad_mean__v04>
  # <compute_mh_y_ple__severity__good_sum>
  # <compute_mh_y_ple__severity__good_mean>
  # <compute_mh_y_ple__severity__bad_sum>
  # <compute_mh_y_ple__severity__bad_mean>
  # <compute_mh_y_ple__severity__good_sum__v01>
  # <compute_mh_y_ple__severity__good_mean__v01>
  # <compute_mh_y_ple__severity__bad_sum__v01>
  # <compute_mh_y_ple__severity__bad_mean__v01>
  # <compute_mh_y_ple__severity__good_sum__v02>
  # <compute_mh_y_ple__severity__good_mean__v02>
  # <compute_mh_y_ple__severity__bad_sum__v02>
  # <compute_mh_y_ple__severity__bad_mean__v02>
  # <compute_mh_y_ple__severity__good_sum__v03>
  # <compute_mh_y_ple__severity__good_mean__v03>
  # <compute_mh_y_ple__severity__bad_sum__v03>
  # <compute_mh_y_ple__severity__bad_mean__v03>
  "exp_internal",
  # <compute_fc_y_eut__ethn_mean>
  "fc_y_eut__ethn_mean_after",
  # <compute_fc_y_eut__ethn_mean>
  "fc_y_eut__ethn_mean_before",
  # <compute_fc_y_eut__ethn_nm>
  "fc_y_eut__ethn_nm_after",
  # <compute_fc_y_eut__ethn_nm>
  "fc_y_eut__ethn_nm_before",
  # <ss_mean_mh_ple>
  # <ss_sum_mh_ple>
  # <ss_nm_mh_ple>
  "fork_vals",
  # <compute_ph_p_dhx_birthweight>
  "fouryear",
  # <compute_ph_p_otbi__tbi1a>
  # <compute_ph_p_otbi__tbi1b>
  # <compute_ph_p_otbi__tbi2>
  # <compute_ph_p_otbi__tbi3>
  # <compute_ph_p_otbi__tbi4>
  # <compute_ph_p_otbi__tbi5>
  "longitudinal",
  # <compute_mh_y_pps__severity_nm>
  # <compute_mh_y_pps__severity_mean>
  "mh_y_pps__bother__yes_count_internal",
  # <compute_mh_y_pps__bother__yes_count>
  # <compute_mh_y_pps__bother__no_count>
  "mh_y_pps__bother_nm_internal",
  # <compute_mh_y_pps__bother_nm>
  "mh_y_pps_count_internal",
  # <compute_nt_y_stq__screen__wknd_nm>
  "nm_other",
  # <compute_nt_p_yst__screen__wkdy_sum>
  "nt_p_yst__wkdy__min_001",
  # <compute_nt_p_yst__screen__wkdy_sum>
  "nt_p_yst__wkdy__min_001__v01",
  # <compute_nt_p_yst__screen__wknd_sum>
  "nt_p_yst__wknd__min_001",
  # <compute_nt_p_yst__screen__wknd_sum>
  "nt_p_yst__wknd__min_001__v01",
  # <create_session_num>
  "num",
  # <compute_ab_g_stc__cohort_ethnrace__meim>
  # <compute_ab_g_stc__cohort_ethn>
  # <compute_ab_g_stc__cohort_race__nih>
  # <compute_ab_g_stc__cohort_ethnrace__leg>
  # <compute_ab_g_stc__cohort_ethnrace__mhisp>
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  # <compute_ph_p_dhx_birthweight>
  # <compute_tlfb_maxdose>
  # <compute_tlfb_mean>
  # <compute_tlfb_totdose>
  # <compute_tlfb_ud>
  # <filter_co_use>
  "participant_id",
  # <compute_ph_p_dhx_birthweight>
  "ph_p_dhx_002__01",
  # <compute_ph_p_dhx_birthweight>
  "ph_p_dhx_002__02",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_002",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_002__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_003",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_003__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_004",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_004__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_005",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__age_005__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc__add_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc__add_001__04",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc__add_001__04__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc__add_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_002",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_002__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_003",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_003__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_004",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_004__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_005",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__loc_005__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__age_001a",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__age_001a__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__age_002a",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__age_003a",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__loc__daz_002",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__loc__daz_003",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__loc_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt__loc_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt_002",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi__rpt_003",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_001",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_001__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_002",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_002__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_003",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_003__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_004",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_004__l",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_005",
  # <compute_ph_p_otbi__loc_tbiage>
  "ph_p_otbi_005__l",
  # <compute_ph_y_bp__dia_nm>
  "ph_y_bp__dia__r01_001",
  # <compute_ph_y_bp__dia_nm>
  "ph_y_bp__dia__r01_002",
  # <compute_ph_y_bp__dia_nm>
  "ph_y_bp__dia__r01_003",
  # <compute_ph_y_bp__hrate_nm>
  "ph_y_bp__hrate__r01_001",
  # <compute_ph_y_bp__hrate_nm>
  "ph_y_bp__hrate__r01_002",
  # <compute_ph_y_bp__hrate_nm>
  "ph_y_bp__hrate__r01_003",
  # <compute_ph_y_bp__sys_nm>
  "ph_y_bp__sys__r01_001",
  # <compute_ph_y_bp__sys_nm>
  "ph_y_bp__sys__r01_002",
  # <compute_ph_y_bp__sys_nm>
  "ph_y_bp__sys__r01_003",
  # <compute_ph_y_mctq__fd__bed_sum>
  "ph_y_mctq__fd__bed__end__36h_t_internal",
  # <compute_ph_y_mctq__fd__bed_sum>
  "ph_y_mctq__fd__bed__start__36h_t_internal",
  # <compute_ph_y_mctq__fd__bed__end__24h_t>
  "ph_y_mctq__fd__sleep__end__24h_t_internal",
  # <compute_ph_y_mctq__fd__bed__end__36h_t>
  # <compute_ph_y_mctq__fd__sleep_dur>
  # <compute_ph_y_mctq__fd__sleep_period>
  "ph_y_mctq__fd__sleep__end__36h_t_internal",
  # <compute_ph_y_mctq__raw__36h_chrono>
  # <compute_ph_y_mctq_chrono>
  # <compute_ph_y_mctq__socjl_rel>
  # <compute_ph_y_mctq__socjl_absl>
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__fd__sleep__mid__36h_t_internal",
  # <compute_ph_y_mctq__fd__sleep__mid__24h_t>
  "ph_y_mctq__fd__sleep__onset__24h_t_internal",
  # <compute_ph_y_mctq__fd__sleep_dur>
  # <compute_ph_y_mctq__fd__sleep_period>
  "ph_y_mctq__fd__sleep__onset__36h_t_internal",
  # <compute_ph_y_mctq__fd__sleep__mid__36h_t>
  # <compute_ph_y_mctq__raw__36h_chrono>
  # <compute_ph_y_mctq_chrono>
  "ph_y_mctq__fd__sleep__onset__36h_t_internal2",
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__fd__sleep__onset__36h_t_internal3",
  # <compute_ph_y_mctq__fd__sleep__onset__24h_t>
  "ph_y_mctq__fd__sleep__start__24h_t_internal",
  # <compute_ph_y_mctq__fd__sleep__onset__36h_t>
  "ph_y_mctq__fd__sleep__start__36h_t_internal",
  # <compute_ph_y_mctq__fd__sleep_dur>
  "ph_y_mctq__fd__sleep__waso_sum_internal",
  # <compute_ph_y_mctq__sleep_dur>
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__fd__sleep_dur_internal",
  # <compute_ph_y_mctq__raw__36h_chrono>
  "ph_y_mctq__fd__sleep_dur_internal2",
  # <compute_ph_y_mctq__fd__bed__end__36h_t>
  # <compute_ph_y_mctq__fd__bed__end__24h_t>
  "ph_y_mctq__fd__sleep_inertia_internal",
  # <compute_ph_y_mctq__fd__sleep__onset__36h_t>
  # <compute_ph_y_mctq__fd__sleep__onset__24h_t>
  "ph_y_mctq__fd__sleep_latent_internal",
  # <compute_ph_y_mctq__fd__sleep__mid__24h_t>
  # <compute_ph_y_mctq__fd__sleep__mid__36h_t>
  # <compute_ph_y_mctq__sleep_loss>
  # <compute_ph_y_mctq__sleep_period>
  "ph_y_mctq__fd__sleep_period_internal",
  # <compute_ph_y_mctq_chrono>
  "ph_y_mctq__fd__sleep_period_internal2",
  # <compute_ph_y_mctq__fd__sleep_latent>
  "ph_y_mctq__fd_003",
  # <compute_ph_y_mctq__fd__sleep_inertia>
  "ph_y_mctq__fd_006",
  # <compute_ph_y_mctq_chrono>
  "ph_y_mctq__fd_007",
  # <compute_ph_y_mctq__sd_count>
  "ph_y_mctq__school_001__01",
  # <compute_ph_y_mctq__sd_count>
  "ph_y_mctq__school_001__01__v1",
  # <compute_ph_y_mctq__sd__bed_sum>
  "ph_y_mctq__sd__bed__end__36h_t_internal",
  # <compute_ph_y_mctq__sd__bed_sum>
  "ph_y_mctq__sd__bed__start__36h_t_internal",
  # <compute_ph_y_mctq__sd__bed__end__24h_t>
  "ph_y_mctq__sd__sleep__end__24h_t_internal",
  # <compute_ph_y_mctq__sd__bed__end__36h_t>
  # <compute_ph_y_mctq__sd__sleep_dur>
  # <compute_ph_y_mctq__sd__sleep_period>
  "ph_y_mctq__sd__sleep__end__36h_t_internal",
  # <compute_ph_y_mctq__socjl_rel>
  # <compute_ph_y_mctq__socjl_absl>
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__sd__sleep__mid__36h_t_internal",
  # <compute_ph_y_mctq__sd__sleep__mid__24h_t>
  "ph_y_mctq__sd__sleep__onset__24h_t_internal",
  # <compute_ph_y_mctq__sd__sleep_dur>
  # <compute_ph_y_mctq__sd__sleep_period>
  "ph_y_mctq__sd__sleep__onset__36h_t_internal",
  # <compute_ph_y_mctq__sd__sleep__mid__36h_t>
  "ph_y_mctq__sd__sleep__onset__36h_t_internal2",
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__sd__sleep__onset__36h_t_internal3",
  # <compute_ph_y_mctq__sd__sleep__onset__24h_t>
  "ph_y_mctq__sd__sleep__start__24h_t_internal",
  # <compute_ph_y_mctq__sd__sleep__onset__36h_t>
  "ph_y_mctq__sd__sleep__start__36h_t_internal",
  # <compute_ph_y_mctq__sd__sleep_dur>
  "ph_y_mctq__sd__sleep__waso_sum_internal",
  # <compute_ph_y_mctq__sleep_dur>
  # <compute_ph_y_mctq_outlier>
  "ph_y_mctq__sd__sleep_dur_internal",
  # <compute_ph_y_mctq__raw__36h_chrono>
  "ph_y_mctq__sd__sleep_dur_internal2",
  # <compute_ph_y_mctq__sd__bed__end__36h_t>
  # <compute_ph_y_mctq__sd__bed__end__24h_t>
  "ph_y_mctq__sd__sleep_inertia_internal",
  # <compute_ph_y_mctq__sd__sleep__onset__36h_t>
  # <compute_ph_y_mctq__sd__sleep__onset__24h_t>
  "ph_y_mctq__sd__sleep_latent_internal",
  # <compute_ph_y_mctq__sd__sleep__mid__24h_t>
  # <compute_ph_y_mctq__sleep_loss>
  # <compute_ph_y_mctq__sd__sleep__mid__36h_t>
  # <compute_ph_y_mctq__sleep_period>
  "ph_y_mctq__sd__sleep_period_internal",
  # <compute_ph_y_mctq_chrono>
  "ph_y_mctq__sd__sleep_period_internal2",
  # <compute_ph_y_mctq__sd__sleep_latent>
  "ph_y_mctq__sd_003",
  # <compute_ph_y_mctq__sd__sleep_inertia>
  "ph_y_mctq__sd_006",
  # <compute_ph_y_mctq__fd_count>
  # <compute_ph_y_mctq__sleep_dur>
  # <compute_ph_y_mctq__sleep_loss>
  # <compute_ph_y_mctq__sleep_period>
  "ph_y_mctq__sd_count_internal",
  # <compute_ph_y_mctq__raw__36h_chrono>
  "ph_y_mctq__sleep_dur_internal",
  # <compute_ph_y_mctq_chrono>
  "ph_y_mctq__sleep_period_internal",
  # <compute_tlfb_mean>
  "qty",
  # <compute_tlfb_maxdose>
  # <compute_tlfb_mean>
  # <compute_tlfb_totdose>
  # <add_combined_substances>
  "quantity",
  # <insert_reference>
  "ref",
  # <ss_tscore>
  "scale_r",
  # <ss_tscore>
  "scale_t",
  # <compute_su_y_nicsre__vape_sum>
  # <compute_su_y_nicsre__vape_nm>
  "score_baseline",
  # <compute_su_y_nicsre__vape_sum>
  # <compute_su_y_nicsre__vape_nm>
  "score_other_events",
  # <compute_caff_weekly>
  "serving",
  # <compute_ab_g_stc__cohort_race__nih>
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  # <compute_fc_p_vs__famil_mean>
  # <compute_fc_p_vs__famil_nm>
  # <compute_fc_p_vs__famil_mean__v01>
  # <compute_fc_p_vs__famil_nm__v01>
  # <compute_fc_y_eut__ethn_mean>
  # <compute_fc_y_eut__ethn_nm>
  # <compute_fc_y_vs__famil_mean>
  # <compute_fc_y_vs__famil_nm>
  # <compute_fc_y_vs__famil_mean__v01>
  # <compute_fc_y_vs__famil_nm__v01>
  # <compute_ph_p_dhx_birthweight>
  # <compute_ph_p_otbi_nm>
  # <compute_ph_p_otbi__loc__30m_count>
  # <compute_ph_p_otbi__loc__30m_nm>
  # <compute_ph_p_otbi__loc_count>
  # <compute_ph_p_otbi__loc_nm>
  # <compute_ph_p_otbi__tbi1a>
  # <compute_ph_p_otbi__tbi1b>
  # <compute_ph_p_otbi__tbi2>
  # <compute_ph_p_otbi__tbi3>
  # <compute_ph_p_otbi__tbi4>
  # <compute_ph_p_otbi__tbi5>
  # <compute_su_y_nicsre__vape_sum>
  # <compute_su_y_nicsre__vape_nm>
  # <compute_tlfb_maxdose>
  # <compute_tlfb_mean>
  # <compute_tlfb_totdose>
  # <compute_tlfb_ud>
  # <filter_co_use>
  # <create_session_num>
  "session_id",
  # <compute_fc_p_vs__famil_mean>
  # <compute_fc_p_vs__famil_nm>
  # <compute_fc_p_vs__famil_mean__v01>
  # <compute_fc_p_vs__famil_nm__v01>
  # <compute_fc_y_vs__famil_mean>
  # <compute_fc_y_vs__famil_nm>
  # <compute_fc_y_vs__famil_mean__v01>
  # <compute_fc_y_vs__famil_nm__v01>
  "session_num",
  # <compute_mh_p_ple__severity__good_sum>
  # <compute_mh_p_ple__severity__good_mean>
  # <compute_mh_p_ple__severity__bad_sum>
  # <compute_mh_p_ple__severity__bad_mean>
  # <compute_mh_p_ple__severity__good_sum__v01>
  # <compute_mh_p_ple__severity__good_mean__v01>
  # <compute_mh_p_ple__severity__bad_sum__v01>
  # <compute_mh_p_ple__severity__bad_mean__v01>
  # <compute_mh_p_ple__severity__good_sum__v02>
  # <compute_mh_p_ple__severity__good_mean__v02>
  # <compute_mh_p_ple__severity__bad_sum__v02>
  # <compute_mh_p_ple__severity__bad_mean__v02>
  # <compute_mh_p_ple__severity__good_sum__v03>
  # <compute_mh_p_ple__severity__good_mean__v03>
  # <compute_mh_p_ple__severity__bad_sum__v03>
  # <compute_mh_p_ple__severity__bad_mean__v03>
  # <compute_mh_p_ple__severity__good_sum__v04>
  # <compute_mh_p_ple__severity__good_mean__v04>
  # <compute_mh_p_ple__severity__bad_sum__v04>
  # <compute_mh_p_ple__severity__bad_mean__v04>
  # <compute_mh_y_ple__severity__good_sum>
  # <compute_mh_y_ple__severity__good_mean>
  # <compute_mh_y_ple__severity__bad_sum>
  # <compute_mh_y_ple__severity__bad_mean>
  # <compute_mh_y_ple__severity__good_sum__v01>
  # <compute_mh_y_ple__severity__good_mean__v01>
  # <compute_mh_y_ple__severity__bad_sum__v01>
  # <compute_mh_y_ple__severity__bad_mean__v01>
  # <compute_mh_y_ple__severity__good_sum__v02>
  # <compute_mh_y_ple__severity__good_mean__v02>
  # <compute_mh_y_ple__severity__bad_sum__v02>
  # <compute_mh_y_ple__severity__bad_mean__v02>
  # <compute_mh_y_ple__severity__good_sum__v03>
  # <compute_mh_y_ple__severity__good_mean__v03>
  # <compute_mh_y_ple__severity__bad_sum__v03>
  # <compute_mh_y_ple__severity__bad_mean__v03>
  "severity_internal",
  # <ss_tscore>
  "sex",
  # <add_combined_substances>
  "standard_factor",
  # <compute_su_y_mjsre_sum>
  "su_y_mjsre__neg_sum",
  # <compute_su_y_mjsre_sum>
  "su_y_mjsre__pos_sum",
  # <filter_co_use>
  "substance",
  # <compute_nt_y_stq__screen__wkdy_sum>
  # <compute_nt_y_stq__screen__wknd_sum>
  "sum_other",
  # <make_static>
  "tmp_col",
  # <compute_ab_g_dyn__cohort_income__hhold__3lvl>
  "tmp_income",
  # <ss_prsum>
  "tmp_mean",
  # <compute_ab_g_stc__cohort_ethnrace__mhisp>
  # <compute_ab_g_stc__cohort_ethnrace__mblack>
  "tmp_new",
  # <compute_ab_g_stc__cohort_race__nih>
  "tmp_nih",
  # <ss_prsum>
  "tmp_prsum",
  # <ss_prsum>
  "tmp_sum",
  # <compute_ph_p_otbi__loc__30m_count>
  # <compute_ph_p_otbi__loc__30m_nm>
  # <compute_ph_p_otbi__loc_count>
  # <compute_ph_p_otbi__loc_nm>
  # <compute_ph_p_otbi__rpt_count>
  # <compute_ph_p_otbi__rpt_nm>
  # <compute_ph_p_otbi__loc__tbiage_nm>
  "tmp_tbi1a",
  # <compute_tlfb_mean>
  "ud",
  # <ss_mean_mh_ple>
  # <ss_sum_mh_ple>
  # <ss_nm_mh_ple>
  "var_valid",
  # <compute_ph_p_dhx_birthweight>
  "var1",
  # <compute_ph_p_dhx_birthweight>
  "var2",
  # <compute_ph_p_dhx_birthweight>
  "weight",
  NULL
))
